### ISSUE TITLE
很好用，如果能更方便的将事项标记完成就更好了

### ISSUE THREAD

**Issue by pisceswb** [ScottXjw/SimplePlan#2]
很好用，感谢作者。
如果能点击打开一个事项后，方便的用按钮将其归类到todo，doing，done，感觉会方便很多。就像新添加的删除按钮

**Comment by ScottXjw** [comment]
下拉菜单这种方式不太方便么？
![image](https://github.com/ScottXjw/SimplePlan/assets/81411248/be71363f-5edc-4da8-8eaa-a10d062f31b3)

**Comment by pisceswb** [comment]
没有新增加的删除键位置方便，如果可行的话，还是在前面加一个待办事项的选项框✅，点击一下就移动到完成，最方便。

**Comment by ScottXjw** [comment]
我明白了，过几天会加上，谢谢你的建议！
