### ISSUE TITLE
列表长按拖动顺序

### ISSUE THREAD

**Issue by qq79248314** [ScottXjw/SimplePlan#3]
能不能加个长按待办，可以拖动顺序，自己排个先后顺序

**Comment by ScottXjw** [comment]
好的，谢谢你的建议！我后面会新增

**Comment by qq79248314** [comment]
对于长文本的，鼠标移动到待办上面，能不能弹出个小框，显示全部文本，类似这样
![image](https://github.com/ScottXjw/SimplePlan/assets/58264024/e07c3251-7dc3-4a68-91bb-deb63e4eb212)
