### ISSUE TITLE
对于长文本的，鼠标移动到待办上面，能不能弹出个小框，显示全部文本，类似这样

### ISSUE THREAD

**Issue by qq79248314** [ScottXjw/SimplePlan#4]
对于长文本的，鼠标移动到待办上面，能不能弹出个小框，显示全部文本，类似这样
![290778330-e07c3251-7dc3-4a68-91bb-deb63e4eb212](https://github.com/ScottXjw/SimplePlan/assets/58264024/5994781d-3546-435f-9534-f1b2a4359cb7)

**Comment by ScottXjw** [comment]
已经OK了，下午可以更新新版本

**Comment by ScottXjw** [comment]
已经上传到github，你可以直接下载覆盖之前的挂件，也可以等待siyuan更新从集市下载
